package classifier

var rolePrefixes = map[string]bool{
	"abuse":     true,
	"admin":     true,
	"billing":   true,
	"careers":   true,
	"contact":   true,
	"hello":     true,
	"help":      true,
	"hr":        true,
	"info":      true,
	"jobs":      true,
	"legal":     true,
	"marketing": true,
	"media":     true,
	"no-reply":  true,
	"noreply":   true,
	"office":    true,
	"postmaster": true,
	"press":     true,
	"privacy":   true,
	"recruiting": true,
	"sales":     true,
	"security":  true,
	"support":   true,
	"team":      true,
	"webmaster": true,
}
